---
# @doc: Установка набора пакетов для Debina, RHEL семейстава ОС
#  - Определить составв пакетов можно в `default/main.yml`
#  - *запустить эту задачу с тегом* `-t packages`

- name: Update apt cache (Debian)
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600
  when: ansible_facts['os_family'] == 'Debian'
  tags:
    - packages

- name: Install common packages
  ansible.builtin.package:
    name: "{{ prepare_common_packages }}"
    state: present
  tags:
    - packages

- name: Install Debian packages
  ansible.builtin.package:
    name: "{{ prepare_debian_packages }}"
    state: present
  when: ansible_facts['os_family'] == 'Debian'
  tags:
    - packages

- name: Install RHEL packages
  ansible.builtin.package:
    name: "{{ prepare_rhel_packages }}"
    state: present
  when: ansible_facts['os_family'] == 'RedHat'
  tags:
    - packages
