---
# @doc: Установка информативного motd сообщения при входе в систему
#  - **Taк же устанавливает переменные**
#  - копирует motd.sh, custom.sh
#  - *запустить эту задачу с тегом* `-t profile`

- name: Deploy global shell environment
  ansible.builtin.copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: '0644'
  loop:
    - { src: custom, dest: /etc/profile.d/custom.sh }
    - { src: motd, dest: /etc/profile.d/motd.sh }
  tags:
    - profile
